export const config = {
    RPC_URL: 'http://localhost:26657',
    REST_URL: 'http://localhost:1317',
    // EXPLORER_URL: 'https://www.mintscan.io/stargaze',
    NETWORK_NAME: 'Hello',
    NETWORK_TYPE: 'hello',
    CHAIN_ID: 'hello',
    CHAIN_NAME: 'Hello',
    COIN_DENOM: 'STAKE',
    COIN_MINIMAL_DENOM: 'ustars',
    COIN_DECIMALS: 6,
    PREFIX: 'cosmos',
    // COIN_TYPE: 118,
    // COINGECKO_ID: 'stargaze',
    DEFAULT_GAS: 250000,
    GAS_PRICE_STEP_LOW: 0.0,
    GAS_PRICE_STEP_AVERAGE: 0.0,
    GAS_PRICE_STEP_HIGH: 0.025,
    // FEATURES: ['stargate', 'ibc-transfer', 'no-legacy-stdTx'],
};
